### ISSUE TITLE
Can you add implementations for Conv3d?

### ISSUE THREAD

**Issue by Techie5879** [EdwinKim3069/WaRP-CIFSL#1]
Current implementation has only implementations for Conv2d. Would be great if Conv3d and related stuff are added

**Comment by EdwinKim3069** [comment]
Hi, thank you for your interest in our research. 
Regrettably, we do not have any immediate plans to implement conv3d. But we believe you might find it straightforward to do so given that Conv3d is a type of linear operation, similar to conv2d counterpart. Referring to conv2d implementation would be helpful to your implementation.

Best regards,
Authors
